
# data related
data_folder: "data"
cam_param: "data/3DOH50K_Parameters.txt"
use_joints_conf: true
interpenetration: false

# output related
output_folder: 'output'
result_folder: 'results'
visualize: False
interactive: True
save_meshes: true
save_images: true
# device
use_cuda: true

# annotation related
#for annotation that contains 3D joint
use_3d: false 
#if the model is smpl, the hip is not for supervision
use_hip: true 
dataset: 'offline'

# model related
model_folder: 'models'
model_type: 'smpllsp' # smpl smpllsp
float_dtype: "float32"
gender: neutral # male female neutral

#prior related
use_vposer: true
prior_folder: 'priors'
body_prior_type: 'l2'

#weight related
data_weights:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
body_pose_prior_weights:
    - 4.04e2
    - 4.04e2
    - 57.4e0
    - 4.78e0
shape_weights:
    - 1.0e2
    - 5.0e1
    - 1.0e1
    - 0.5e1
coll_loss_weights:
    - 0.0
    - 0.0
    - 0.01
    - 1.0
    
# optimization related
rho: 100
optim_type: 'lbfgsls'
ftol: 1e-9
gtol: 1e-9
lr: 1.0
# Max number of optimization iterations
maxiters: 30

# joints_to_ign:
    # - 1
    # - 9
    # - 12



# 
# use_pca: True
# use_hands: False
# use_face: False
# flat_hand_mean: False
# # The number of mixture components for the pose prior
# num_gaussians: 8
# focal_length: 5000
# num_pca_comps: 12
# # The constant for the robust loss function
# 
# 
# df_cone_height: 0.0001
# # Upper arms and Spine 2
# # Neck and jaw
# ign_part_pairs: ["9,16", "9,17", "6,16", "6,17", "1,2", "12,22"]
# penalize_outside: True
# max_collisions: 128
# # LBFGS with line search

# 
# 


